server:
 port: 6688

dubboservice:
  datasource:
      write:
        url: jdbc:mysql://127.0.0.1:3306/zaioublog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 20
        initial-size: 1
        min-idle: 3
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x' FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
        # 合并多个DruidDataSource的监控数据
        #spring.datasource.useGlobalDataSourceStat=true
      read:
        url: jdbc:mysql://127.0.0.1:3306/zaioublog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 20
        initial-size: 1
        min-idle: 3
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x' FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
        # 合并多个DruidDataSource的监控数据
        #spring.datasource.useGlobalDataSourceStat=true




mybatis:
  mapperLocations: classpath:mapper/*.xml


spring: datasource:initialize:false

#session store type是用来存放session的存储方式，目前Spring boot中只支持Redis方式。
#由于本应用暂无需将session放入redis的需求，故这里就可以将session store type设置为none
#如果使用redis存储session:application.properties配置 spring.session.store-type=redis
#http://www.cnblogs.com/arthy/p/6902960.html
#http://www.cnblogs.com/Impulse/archive/2012/02/03/2337479.html
spring.session.store-type: none
